### PR TITLE
Packet CSI Helm Chart

### PR DESCRIPTION
**Pull request by jmarhee**

### CODE REVIEW

**Comment by jmarhee** [comment]
CC: @deitch @vielmetti 

Heavily WIP, but this chart applies without issue as-is, so feel free to comment, etc.

**Comment by jmarhee** [comment]
Please disregard the test failures, I'll squash these once I get CI in order.

**Review by deitch — APPROVED** [review]
If it works as is, then no need to change anything. Is the only part we templated the CSI version?

How do we handle that the manifests themselves might change? Is that just an update to the helm chart?

**Comment by jmarhee** [comment]
Yeah, only the release is templated at the moment; as it exists right now, I just used the release's manifests as-is, so the helm chart just needs to get updated if those change-- I'm sure there's a better way to handle this (maybe pull in the release's manifests as a subchart template or something), but could be something we address later (there's a couple of other enhancements that can go along with this that I'll open issues for).

**Comment by deitch** [comment]
Sounds good!

**Pull request merged**
